#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

./Allrun.pre

runApplication decomposePar

runParallel setFields

runParallel $(getApplication)

runApplication reconstructPar

runApplication foamToVTK

runApplication postProcess -funcs \
    "(minMaxComponents(U) minMaxMagnitude(U))" -latestTime

#------------------------------------------------------------------------------
